<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '',
    'City Ward Town Village Name Kana' => '市区町村名カナ',
    'City Ward Town Village Name Kanji' => '市区町村名',
    'Create Zipcode' => '',
    'Delete' => '',
    'Has Banchi' => '番地有無',
    'Has Chome' => '丁目有無',
    'ID' => '',
    'Key' => 'キー',
    'Local Public Entity Code' => '地方公共団体コード',
    'Modified' => '更新フラグ',
    'Modified Reason' => '変更理由',
    'Multiple Town Area' => '複数町域',
    'Multiple Zip Code' => '複数郵便番号',
    'Old Zip Code' => '旧郵便番号',
    'Prefecture Name Kana' => '都道府県名カナ',
    'Prefecture Name Kanji' => '都道府県名',
    'Reset' => '',
    'Save' => '',
    'Search' => '',
    'Town Area Name Kana' => '町域名カナ',
    'Town Area Name Kanji' => '町域名',
    'Update' => '',
    'Update Zipcode: {name}' => '',
    'Value' => '値',
    'Zip Code' => '郵便番号',
    'Zipcodes' => '郵便番号',
];
